// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaKFbl6UfrJByJC0DlXh1TJ4YNzEHS1ZM',
    appId: '1:489298115604:web:0512b96327fb9dab683b01',
    messagingSenderId: '489298115604',
    projectId: 'joinme-app-9a6da',
    authDomain: 'joinme-app-9a6da.firebaseapp.com',
    storageBucket: 'joinme-app-9a6da.firebasestorage.app',
    measurementId: 'G-CGDG5RNRWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5ch28ttHUnQ6S0aIxrtgeFNqCDKe-bEw',
    appId: '1:489298115604:android:9848386cdd73b2ed683b01',
    messagingSenderId: '489298115604',
    projectId: 'joinme-app-9a6da',
    storageBucket: 'joinme-app-9a6da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWU9IiAaHRPT1iV1IhkqM1kqiQDW5PLLc',
    appId: '1:489298115604:ios:a78e607717d2b593683b01',
    messagingSenderId: '489298115604',
    projectId: 'joinme-app-9a6da',
    storageBucket: 'joinme-app-9a6da.firebasestorage.app',
    iosBundleId: 'com.example.joinmeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWU9IiAaHRPT1iV1IhkqM1kqiQDW5PLLc',
    appId: '1:489298115604:ios:a78e607717d2b593683b01',
    messagingSenderId: '489298115604',
    projectId: 'joinme-app-9a6da',
    storageBucket: 'joinme-app-9a6da.firebasestorage.app',
    iosBundleId: 'com.example.joinmeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaKFbl6UfrJByJC0DlXh1TJ4YNzEHS1ZM',
    appId: '1:489298115604:web:4c4262df4792089b683b01',
    messagingSenderId: '489298115604',
    projectId: 'joinme-app-9a6da',
    authDomain: 'joinme-app-9a6da.firebaseapp.com',
    storageBucket: 'joinme-app-9a6da.firebasestorage.app',
    measurementId: 'G-LRN7DMLF1M',
  );
}
